### ISSUE TITLE
EAP  2024.2 exceptions on debugger startup

### ISSUE THREAD

**Issue by bedge** [BashSupport-Pro/bashsupport-pro#168]
Yes, I'm using an EAP version. There's other WSL things that don't work in the release (blame JetBrains).

Don't even know if this is the "real" issue, but I can't step past the 1st line using this combination so I'm reporting oner at a time.
Will append other exceptions/errors I find in the "start debugger" workflow.

Starting a bashdb session dumps this in the log:

```
2024-07-19 17:39:49,691 [20659539]   INFO - #c.i.u.WinFocusStealer - Foreground lock timeout set to 200000
2024-07-19 17:39:50,837 [20660685]   INFO - #c.i.e.wsl - WSL mount root for Ubuntu is /mnt/ (done in 1108 ms)
2024-07-19 17:39:50,854 [20660702]   INFO - #c.i.u.WinFocusStealer - Foreground lock timeout set to 0
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - Exception in thread "BashSupport Pro debugger tasks" java.lang.NoClassDefFoundError: org/jetbrains/debugger/DebuggerSupportUtils
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at pro.bashsupport.shell.jn.U(jn.java:92)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at pro.bashsupport.shell.jn.invoke(jn.java:74)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:93)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1$lambda$0(cancellableReadAction.kt:31)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1(cancellableReadAction.kt:29)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:27)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:93)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:77)
2024-07-19 17:39:53,097 [20662945]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:43)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5c6e055e, BoundedExecutor(4); inProgress: 1; name: BashSupport Pro debugger tasks]
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - Caused by: java.lang.ClassNotFoundException: org.jetbrains.debugger.DebuggerSupportUtils PluginClassLoader(plugin=PluginDescriptor(name=BashSupport Pro, id=pro.bashsupport, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2024.2\plugins\bashsupport-pro, version=4.2.1.242, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, moduleName=intellij.terminal.sh, descriptorPath=intellij.terminal.sh.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\terminal, version=242.20224.38, package=org.jetbrains.plugins.terminal.sh, isBundled=true), PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, moduleName=intellij.terminal/cloud, descriptorPath=intellij.terminal.cloud.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\terminal, version=242.20224.38, package=org.jetbrains.plugins.terminal.cloud, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.xml, descriptorPath=intellij.markdown.xml.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.xml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.spellchecker, descriptorPath=intellij.markdown.spellchecker.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.spellchecker, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.model, descriptorPath=intellij.markdown.model.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.model, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.images, descriptorPath=intellij.markdown.images.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.images, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter.yaml, descriptorPath=intellij.markdown.frontmatter.yaml.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.frontmatter.yaml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter.toml, descriptorPath=intellij.markdown.frontmatter.toml.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.frontmatter.toml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter, descriptorPath=intellij.markdown.frontmatter.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.frontmatter, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.fenceInjection, descriptorPath=intellij.markdown.fenceInjection.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown.fenceInjection, isBundled=true), PluginDescriptor(name=Copyright, id=com.intellij.copyright, moduleName=intellij.copyright.vcs, descriptorPath=intellij.copyright.vcs.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\copyright, version=242.20224.38, package=com.maddyhome.idea.copyright.vcs, isBundled=true), PluginDescriptor(name=Grazie Lite, id=tanvd.grazi, moduleName=intellij.grazie.yaml, descriptorPath=intellij.grazie.yaml.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\grazie, version=242.20224.38, package=com.intellij.grazie.ide.language.yaml, isBundled=true), PluginDescriptor(name=Grazie Lite, id=tanvd.grazi, moduleName=intellij.grazie.xml, descriptorPath=intellij.grazie.xml.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\grazie, version=242.20224.38, package=com.intellij.grazie.ide.language.xml, isBundled=true), PluginDescriptor(name=Grazie Lite, id=tanvd.grazi, moduleName=intellij.grazie.properties, descriptorPath=intellij.grazie.properties.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\grazie, version=242.20224.38, package=com.intellij.grazie.ide.language.properties, isBundled=true), PluginDescriptor(name=Grazie Lite, id=tanvd.grazi, moduleName=intellij.grazie.markdown, descriptorPath=intellij.grazie.markdown.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\grazie, version=242.20224.38, package=com.intellij.grazie.ide.language.markdown, isBundled=true), PluginDescriptor(name=Grazie Lite, id=tanvd.grazi, moduleName=intellij.grazie.json, descriptorPath=intellij.grazie.json.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\grazie, version=242.20224.38, package=com.intellij.grazie.ide.language.json, isBundled=true), PluginDescriptor(name=Grazie Lite, id=tanvd.grazi, moduleName=intellij.grazie.java, descriptorPath=intellij.grazie.java.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\grazie, version=242.20224.38, package=com.intellij.grazie.ide.language.java, isBundled=true), PluginDescriptor(name=Docker, id=Docker, moduleName=intellij.clouds.docker.ssh, descriptorPath=intellij.clouds.docker.ssh.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\clouds-docker-impl, version=242.20224.38, package=com.intellij.docker.ssh, isBundled=true), PluginDescriptor(name=Docker, id=Docker, moduleName=intellij.clouds.docker.remoteRun, descriptorPath=intellij.clouds.docker.remoteRun.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\clouds-docker-impl, version=242.20224.38, package=com.intellij.docker.remote, isBundled=true), PluginDescriptor(name=Docker, id=Docker, moduleName=intellij.clouds.docker.kubernetes, descriptorPath=intellij.clouds.docker.kubernetes.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\clouds-docker-impl, version=242.20224.38, package=com.intellij.docker.kubernetes, isBundled=true), PluginDescriptor(name=Docker, id=Docker, moduleName=intellij.clouds.docker.java, descriptorPath=intellij.clouds.docker.java.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\clouds-docker-impl, version=242.20224.38, package=com.intellij.docker.java, isBundled=true), PluginDescriptor(name=Docker, id=Docker, moduleName=intellij.clouds.docker.file, descriptorPath=intellij.clouds.docker.file.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\clouds-docker-impl, version=242.20224.38, package=com.intellij.docker.dockerFile, isBundled=true), PluginDescriptor(name=Docker, id=Docker, moduleName=intellij.clouds.docker.compose, descriptorPath=intellij.clouds.docker.compose.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\clouds-docker-impl, version=242.20224.38, package=com.intellij.docker.composeFile, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\lib, version=242.20224.38, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\lib, version=242.20224.38, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\lib, version=242.20224.38, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\lib, version=242.20224.38, package=null, isBundled=true), PluginDescriptor(name=YAML, id=org.jetbrains.plugins.yaml, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\yaml, version=242.20224.38, package=org.jetbrains.yaml, isBundled=true), PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\terminal, version=242.20224.38, package=org.jetbrains.plugins.terminal, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\markdown, version=242.20224.38, package=org.intellij.plugins.markdown, isBundled=true), PluginDescriptor(name=Grazie Lite, id=tanvd.grazi, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\grazie, version=242.20224.38, package=com.intellij.grazie, isBundled=true), PluginDescriptor(name=Docker, id=Docker, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\clouds-docker-impl, version=242.20224.38, package=com.intellij.docker, isBundled=true), PluginDescriptor(name=Copyright, id=com.intellij.copyright, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\copyright, version=242.20224.38, package=null, isBundled=true), PluginDescriptor(name=IntelliLang, id=org.intellij.intelliLang, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 242.19890.14\plugins\platform-langInjection
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - , version=242.20224.38, package=null, isBundled=true), )
2024-07-19 17:39:53,098 [20662946]   INFO - STDERR - 	... 24 more
```

IntelliJ IDEA 2024.2 Beta (Ultimate Edition)
Build #IU-242.20224.38, built on July 11, 2024
Licensed to IntelliJ IDEA EAP user: Bruce Edge
Expiration date: August 10, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  MultiHighlight (3.2.0)
  org.intellij.plugins.hcl (242.20224.22)
  PythonCore (242.20224.38)
  com.mrootx.idea (1.0.2)
  awesome.console (0.1337.12)
  EclipseCodeFormatter (23.4.223.000.0-Eclipse_2023-03)
  AntSupport (242.20224.23)
  com.ahmed3elshaer.true-black-theme (1.4.5)
  Pythonid (242.20224.38)
  com.intellij.plugin.adernov.powershell (2.6.1)
  GrepConsole (13.0.2-IJ2023.3)
  com.intellij.ml.llm (242.20224.39)
  PlantUML integration (7.10.1-IJ2023.2)
  pro.bashsupport (4.2.1.242)
  MavenRunHelper (4.28.0-IJ2022.2)
  org.exbin.deltahex.intellij (0.2.10.1)
  com.intellij.bigdatatools.core (242.20224.38)
  com.intellij.bigdatatools.binary.files (242.20224.23)
  com.intellij.bigdatatools.rfs (242.20224.38)
  git-extended-update-index (0.1.3)
  com.datadog.intellij (1.4.4)
  com.mallowigi (97.0.0)
  com.github.copilot (1.5.15.6094)
  zielu.gittoolbox (500.2.10+242)
Kotlin: 242.20224.38-IJ

**Comment by bedge** [comment]
Debugger setup:
![image](https://github.com/user-attachments/assets/f035c9dd-d997-44ad-8ff9-c4ee04099da0)

![image](https://github.com/user-attachments/assets/d621563c-79cf-4d99-8679-da88ad62cd9a)

This script:
```
#!/bin/bash

base="$(dirname $0)"
. ${base}/jfrog-api.sh
# Test update all to release-2.5

#jfrog_get_build_component_list upp 3.0-5

jfrog_create_release upp 3.0
```

I can break on the 1st line:
```
base="$(dirname $0)"
```
Then if I "step over" that line, it never finishes:
![image](https://github.com/user-attachments/assets/1f8f9c21-8c24-4363-8b53-4b9f9322c632)

**Comment by jansorg** [comment]
Thanks! One the last eaps removed a class from the SDK, which breaks the debugger. I'll publish a fixed version for 2024.2 eap shortly.

**Comment by bedge** [comment]
Fantastic, thank you.

**Comment by jansorg** [comment]
4.2.2 is available now with a fix. Please reopen this issue if the problem is still present.
