### ISSUE TITLE
Debugger hang ups in IntelliJ IDEA 2024.1.4

### ISSUE THREAD

**Issue by bedge** [BashSupport-Pro/bashsupport-pro#169]
The debugger is hanging up like it's waiting for a command or function to complete. There's always an IDE log stack trace present when this happens.
Doesn't always happen in the same place. Sometimes I'm not able to get into the first function call.

The one thing that may be related is I'm using a small wrapper shell script that:
1. Sources the code I'm testing
2. Runs a function from the sourced code

eg:
```
#!/bin/bash

base="$(dirname $0)"
. ${base}/upath-util.sh

# up_repo_update_all release-2.5
jfrog_get_build_components upp 3.0-5
```
I add random method calls here as a way to isolate the function I'm testing. 

Here's one of the traces:
```
2024-07-20 08:41:57,449 [ 238068]   INFO - #c.j.r.f.FollowMeManager - Unregister user (name: 'edgeb1', clientId: Host)
2024-07-20 08:41:57,451 [ 238070]   INFO - #c.i.o.w.i.WindowManagerImpl - === Release(true) frame on closed project ===
2024-07-20 08:41:57,491 [ 238110]   WARN - #com.datadog.intellij.staticAnalysis.config.StaticAnalysisConfigProvider - com.datadog.intellij.staticAnalysis.config.StaticAnalysisConfigProvider@59ce5bbf
2024-07-20 08:41:57,494 [ 238113]   INFO - #zielu.gittoolbox.blame.cache.xodus - Deleted 0 expired files
2024-07-20 08:41:57,494 [ 238113]   INFO - #zielu.gittoolbox.blame.cache.xodus - Deleted 0 expired revisions
2024-07-20 08:41:58,534 [ 239153]   INFO - #o.j.k.i.s.r.KotlinCompilerReferenceIndexStorage - KCRI storage is closed (didn't exist)
2024-07-20 08:41:58,538 [ 239157]   INFO - #c.i.c.b.CompilerReferenceServiceBase - backward reference index reader is closed (didn't exist)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - Exception in thread "BashSupport Pro debugger tasks" java.lang.StringIndexOutOfBoundsException: begin 0, end 145, length 1
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at java.base/java.lang.String.substring(String.java:2709)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at pro.bashsupport.shell.sx.B(sx.java:142)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at pro.bashsupport.shell.sx.v(sx.java:81)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at pro.bashsupport.shell.sx.t(sx.java:58)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at pro.bashsupport.shell.q0.B(q0.java:14)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at pro.bashsupport.shell.of.invokeSuspend(of.java)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2024-07-20 08:42:43,308 [ 283927]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2024-07-20 08:42:43,309 [ 283928]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2024-07-20 08:42:43,309 [ 283928]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-20 08:42:43,309 [ 283928]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@22e940cf, BoundedExecutor(4); inProgress: 1; name: BashSupport Pro debugger tasks]
2024-07-20 08:43:20,856 [ 321475]   INFO - #c.i.j.n.n.WorkingDirectoryDependentNpmPackageVersionManager - Version fetched successfully: 9.5.1; command: "C:\Program Files\nodejs\npm.cmd" --version, duration: 844ms
```

Here's the cfg dump:
```
IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 20, 2024
Licensed to Roche ltd / Bruce Edge
Subscription is active until December 31, 2024.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  MultiHighlight (3.2.0)
  org.intellij.plugins.hcl (241.17890.8)
  com.mrootx.idea (1.0.2)
  awesome.console (0.1337.12)
  color.scheme.Tomorrow Dark (0.2)
  color.scheme.EclipseDarkLike (1.1)
  com.vecheslav.darculaDarkerTheme (1.2.0)
  net.antelle.intellij-xcode-dark-theme (1.2.4)
  Twitch Dark Theme (1.2.6)
  com.ahmed3elshaer.true-black-theme (1.4.5)
  Pythonid (241.18034.62)
  com.samdark.intellij-visual-studio-code-dark-plus (2.8)
  EclipseCodeFormatter (23.4.223.000.0-Eclipse_2023-03)
  com.intellij.plugin.adernov.powershell (2.6.1)
  GrepConsole (13.0.2-IJ2023.3)
  PlantUML integration (7.10.1-IJ2023.2)
  pro.bashsupport (4.2.1.241)
  MavenRunHelper (4.28.0-IJ2022.2)
  com.intellij.ml.llm (241.18034.12)
  git-extended-update-index (0.1.3)
  com.mallowigi (97.0.0)
  com.github.copilot (1.5.16.6140)
  com.datadog.intellij (1.4.5)
  com.intellij.bigdatatools.core (241.18034.62)
  zielu.gittoolbox (500.2.10+233)
Kotlin: 241.18034.62-IJ
```

**Comment by bedge** [comment]
Apologize for the spurious tickets. Now it's working...
I'll close if I can't replicate.
Was 100% consistent a couple of hours.

**Comment by bedge** [comment]
Happened again:
```

2024-07-20 09:08:52,839 [1853458] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Unhandled exception in [StandaloneCoroutine{Cancelling}@44d503fe, BoundedExecutor(4); inProgress: 1; name: BashSupport Pro debugger tasks]
java.lang.StringIndexOutOfBoundsException: begin 0, end 252, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
	at java.base/java.lang.String.substring(String.java:2709)
	at pro.bashsupport.shell.sx.B(sx.java:142)
	at pro.bashsupport.shell.sx.v(sx.java:81)
	at pro.bashsupport.shell.sx.t(sx.java:58)
	at pro.bashsupport.shell.q0.B(q0.java:14)
	at pro.bashsupport.shell.of.invokeSuspend(of.java)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-20 09:08:52,839 [1853458] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - IntelliJ IDEA 2024.1.4  Build #IU-241.18034.62
2024-07-20 09:08:52,840 [1853459] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-07-20 09:08:52,840 [1853459] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - OS: Windows 11
2024-07-20 09:08:52,840 [1853459] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Plugin to blame: BashSupport Pro version: 4.2.1.241
2024-07-20 09:08:52,840 [1853459] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Last Action: StepOver
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - Exception in thread "BashSupport Pro debugger tasks" java.lang.StringIndexOutOfBoundsException: begin 0, end 252, length 1
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.lang.String.substring(String.java:2709)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at pro.bashsupport.shell.sx.B(sx.java:142)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at pro.bashsupport.shell.sx.v(sx.java:81)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at pro.bashsupport.shell.sx.t(sx.java:58)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at pro.bashsupport.shell.q0.B(q0.java:14)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at pro.bashsupport.shell.of.invokeSuspend(of.java)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-20 09:08:52,841 [1853460]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@44d503fe, BoundedExecutor(4); inProgress: 1; name: BashSupport Pro debugger tasks]
```

What's also interesting is that I can still flip over to the debug console and hit <CR> and it advances to the next line. It's the GUI representation of this process that appears to have detached from the debugger session.
(Note: I'm not at all familiar with bashdb direct use).

**Comment by bedge** [comment]
I was able to get to the end of this session, so I won't be using it again until I need to. 
I expect there's a lot of churn between the APIs and new releases that make keeping the plugins in sync a royal PITA. 
I'll report anything I run into.

**Comment by jansorg** [comment]
Thanks, this seems to be a bug in the plugin. I'll get this fixed, too.

**Comment by jansorg** [comment]
I've fixed this, but would still like to know why this is happening.
Are you using WSL? Which distribution are you running and which version of Bash is used?

It seems like the bashdb debugger is returning variable information in an expected format.

**Comment by bedge** [comment]
Yes, WSL. I had to switch from mac to windows recently - a seriously mixed blessing.

  WSL2, Ubuntu 22.04.4 
```
✦ ❯ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

**Comment by jansorg** [comment]
4.2.2 is available now with a fix. Please reopen this issue if the problem is still present.
